### PR TITLE
Bring `elm` branch up-to-date with `master` to fix ihp-new for elm

### PR DESCRIPTION
**Pull request by james64**
There is an issue with `ihp-new --elm myProject` command tracked as issue here: digitallyinduced/ihp#1955 .

This pr merges `master` branch into `elm`. There were merge conflicts in `start` and `default.nix` files which were resolved in favor of `master` version.

Merged version were tested by running edited local copy of `ihp-new` bash script which pointed to my version of boilerplate git repo. This successfully created a project files. `start` script successfully started dev server, web based ide and dummy version of application itself. Based on initial webapp msg elm is not working but that is a different issue.

### CODE REVIEW

**Comment by james64** [comment]
I have realized that elam not working might be some functionality of former start script which was not migrated to devenv setup. I will try to dig in later

**Comment by mpscholten** [comment]
Thanks :+1:

I think the `npm run run-dev-elm` in the start script needs to be added to the devenv configuration in `flake.nix`:

```nix
                # Custom configuration that will start with `devenv up`
                devenv.shells.default = {
                    # Start Mailhog on local development to catch outgoing emails
                    # services.mailhog.enable = true;

                    languages.elm.enable = true;

                    processes = {
                        frontend.exec = "parcel watch elm/index.js --out-dir static/elm";
                    };
                };
```

**Comment by james64** [comment]
I have added npm build command to `flake.nix` as suggested. This works for me now. Only it looks like `npm` has to be installed on the system already and `npm install` needs to be run manually.

@mpscholten do you want me to add `npm` to elm tooling with auto run for `npm install`? Or do you want to merge it as is? Because of my own curiosity I will try to do these things. It's just that it will take me some time. I need to learn this devenv thing as it's new to me. Let me know

**Comment by mpscholten** [comment]
Best option seems to be both: we merge the current PR as is, so elm is working again. And I'd be happy to merge a second PR that improves the npm workflow. Ideally removing the need for a manual `npm install` :)

**Review by mpscholten — APPROVED** [review]

**Pull request merged**
