### PR TITLE
Add an IHP terraform configuration for AWS

### PR DESCRIPTION
**Pull request by mokshasoft**

### CODE REVIEW

**Comment by mpscholten** [comment]
Given most people don't use terraform, I was thinking we could put this into a separate branch of this repo (e.g. we have the same with [`elm`](https://github.com/digitallyinduced/ihp-boilerplate/tree/elm) and `purescript-halogen`). This way we still have it for the people that use terraform, but don't blow up the standard IHP distribution for everyone else. WDYT?

**Comment by mokshasoft** [comment]
Yes, that sounds like a good idea. In case it gets wide use it can always be merged to the master branch later.

**Comment by mokshasoft** [comment]
I couldn't edit the pull request to change the base branch to IaC-aws since it doesn't exist. Do I have to do something or can you handle it yourself?

**Comment by mokshasoft** [comment]
When this is merged I'll update the documentation PR so that it links to the correct source.

**Comment by mpscholten** [comment]
just created the `IaC-aws` branch and also gave you write permissions to the repo 👍

**Comment by mokshasoft** [comment]
Thanks. I will decline the write permission since I don't have TFA setup at the moment. The base is now updated to IaC-aws.

**Comment by mpscholten** [comment]
Thanks 👍

**Pull request merged**
